[context.production.environment]
HUGO_BASEURL = "https://versicolor.io"

[context.deploy-preview]
command = "hugo  --gc --minify --buildFuture --buildDrafts -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo  --gc --minify --buildFuture --buildDrafts -b $DEPLOY_PRIME_URL"
